---
version: 1

dependencies:
  galaxy: ee_requirements.yml
  python: ee_requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN pip install pip --upgrade
    RUN whoami
    RUN cat /etc/os-release
  append:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc
